FROM ubuntu as base

ARG CONTAINER_UID
ARG CONTAINER_GID

RUN apt-get update \
 && apt-get install -y \
        sudo \
        git \
        curl \
        jq \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# init container
ADD run/devcontainer/containers/workspace/init-container /init-container

# init container: vscode local terminal
ENV INIT_CONTAINER_VSCODE_LOCAL_TERMINAL=1

# init container: workspace
ENV INIT_CONTAINER_WORKSPACE=1

# init container: npm
ENV INIT_CONTAINER_NPM=1
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*
RUN node -v && npm -v

# init container: uv
ENV INIT_CONTAINER_UV=1
ENV UV_INSTALL_DIR="/workspace/run/devcontainer/.caches/uv"
ENV PATH="${UV_INSTALL_DIR}:${PATH}"

# init container: claude code
ENV INIT_CONTAINER_CLAUDE_CODE=1
ENV CLAUDE_CONFIG_DIR="/workspace/run/devcontainer/.caches/claude"
RUN npm config set os linux
RUN npm install -g @anthropic-ai/claude-code
