services:
  workspace:
    build:
      context: ../..
      dockerfile: ./run/containers/workspace/Dockerfile
      args:
        - CONTAINER_USER
        - CONTAINER_UID
        - CONTAINER_GID
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - WORKSPACE_ROOT=/workspace
      - TARGET_ENV=workspace
    command: sleep infinity
    volumes:
      - ../..:/workspace
